import type { Recommendation } from "./types";
import { deriveLabelFlags } from "./matching";
import { estimateEffort } from "./effort";

const baseRecommendations: Omit<Recommendation, "effort">[] = [
  {
    id: "1-23178",
    issueNumber: 23178,
    issueTitle:
      "FP Syntax Error in Expansion: expected integer, identifier, `self`, `super`, `crate`, or `Self`",
    issueUrl: "https://github.com/rust-lang/rust-analyzer/issues/23178",
    labels: ["good first issue", "E-easy", "A-parser", "C-bug"],
    comments: 1,
    author: "matthiaskrgr",
    repository: "rust-analyzer",
    organization: "rust-lang",
    repoDescription: "An experimental Rust compiler front-end for IDEs.",
    repoLanguage: "Rust",
    repoStars: 9800,
    repoTopics: ["rust", "ide", "compiler"],
    whyRecommended: [
      "Uses Rust, which matches your selected language.",
      "Marked as a good first issue — ideal for new contributors.",
      "Well-established project with 9,800 stars.",
    ],
    difficulty: "beginner",
    matchedLabels: ["Rust", "Beginner Friendly", "Bug Fix"],
    readme: {
      hasContributionGuide: true,
      setupComplexity: "moderate",
      techStack: ["rust", "compiler"],
      architectureKeywords: ["layered-architecture"],
    },
    matchScore: {
      total: 92,
      breakdown: [
        { label: "Rust primary", points: 30, category: "language" as const },
        {
          label: "Compilers interest",
          points: 20,
          category: "interest" as const,
        },
        { label: "Good First Issue", points: 15, category: "issue" as const },
        {
          label: "Established project",
          points: 12,
          category: "project" as const,
        },
        {
          label: "Contribution guide",
          points: 8,
          category: "project" as const,
        },
        { label: "Trending now", points: 7, category: "project" as const },
      ],
    },
    readinessScore: 90,
  },
  {
    id: "2-500",
    issueNumber: 500,
    issueTitle: "Add retry logic for failed network requests",
    issueUrl: "https://github.com/tokio-rs/tokio/issues/500",
    labels: ["help wanted", "enhancement"],
    comments: 5,
    author: "alice",
    repository: "tokio",
    organization: "tokio-rs",
    repoDescription:
      "An asynchronous runtime for the Rust programming language.",
    repoLanguage: "Rust",
    repoStars: 28400,
    repoTopics: ["rust", "async", "networking"],
    whyRecommended: [
      "Primary language is Rust — matches your stack.",
      "Open for community contributions.",
      "Established project with 28,400 stars.",
      "Active discussion on approach.",
    ],
    difficulty: "intermediate",
    matchedLabels: ["Rust", "Help Wanted"],
    readme: {
      hasContributionGuide: true,
      setupComplexity: "simple",
      techStack: ["rust", "async", "tokio"],
      architectureKeywords: ["async", "non-blocking"],
    },
    matchScore: {
      total: 57,
      breakdown: [
        { label: "Rust primary", points: 30, category: "language" as const },
        {
          label: "Established project",
          points: 12,
          category: "project" as const,
        },
        {
          label: "Contribution guide",
          points: 5,
          category: "project" as const,
        },
        { label: "Active discussion", points: 3, category: "issue" as const },
        { label: "Help Wanted", points: 5, category: "issue" as const },
        { label: "Trending now", points: 7, category: "project" as const },
      ],
    },
    readinessScore: 75,
  },
  {
    id: "3-1200",
    issueNumber: 1200,
    issueTitle: "Improve documentation for Lua API",
    issueUrl: "https://github.com/neovim/neovim/issues/1200",
    labels: ["documentation", "good first issue"],
    comments: 3,
    author: "bob",
    repository: "neovim",
    organization: "neovim",
    repoDescription: "Hyperextensible Vim-based text editor.",
    repoLanguage: "C",
    repoStars: 86200,
    repoTopics: ["editor", "vim", "lua"],
    whyRecommended: [
      "Documentation contribution — great way to learn the codebase.",
      "Marked as a good first issue — ideal for new contributors.",
      "Established project with 86,200 stars.",
      "Has a contribution guide — onboarding is clear.",
    ],
    difficulty: "beginner",
    matchedLabels: ["Beginner Friendly", "Documentation"],
    readme: {
      hasContributionGuide: true,
      setupComplexity: "complex",
      techStack: ["c", "lua"],
      architectureKeywords: ["plugin-system", "event-driven"],
    },
    matchScore: {
      total: 42,
      breakdown: [
        { label: "Good First Issue", points: 15, category: "issue" as const },
        { label: "Documentation", points: 8, category: "issue" as const },
        {
          label: "Established project",
          points: 12,
          category: "project" as const,
        },
        {
          label: "Contribution guide",
          points: 8,
          category: "project" as const,
        },
        { label: "Complex setup", points: -3, category: "project" as const },
        { label: "Trending now", points: 7, category: "project" as const },
      ],
    },
    readinessScore: 70,
  },
  {
    id: "4-800",
    issueNumber: 800,
    issueTitle: "Implement compile-time bounds checking for slice access",
    issueUrl: "https://github.com/ziglang/zig/issues/800",
    labels: ["enhancement", "compiler"],
    comments: 12,
    author: "charlie",
    repository: "zig",
    organization: "ziglang",
    repoDescription: "General-purpose programming language and toolchain.",
    repoLanguage: "Zig",
    repoStars: 38100,
    repoTopics: ["zig", "compiler", "systems"],
    whyRecommended: [
      "Established project with 38,100 stars.",
      "Has a contribution guide — onboarding is clear.",
      "High engagement — 12 comments.",
    ],
    difficulty: "advanced",
    matchedLabels: [],
    readme: {
      hasContributionGuide: true,
      setupComplexity: "moderate",
      techStack: ["zig", "compiler"],
      architectureKeywords: ["pipeline"],
    },
    matchScore: {
      total: 27,
      breakdown: [
        {
          label: "Established project",
          points: 12,
          category: "project" as const,
        },
        {
          label: "Contribution guide",
          points: 5,
          category: "project" as const,
        },
        { label: "High engagement", points: 1, category: "issue" as const },
        { label: "Trending now", points: 7, category: "project" as const },
      ],
    },
    readinessScore: 55,
  },
  {
    id: "5-3000",
    issueNumber: 3000,
    issueTitle: "Add support for custom file watchers",
    issueUrl: "https://github.com/denoland/deno/issues/3000",
    labels: ["help wanted", "feat", "good first issue"],
    comments: 8,
    author: "dave",
    repository: "deno",
    organization: "denoland",
    repoDescription: "A modern runtime for JavaScript and TypeScript.",
    repoLanguage: "Rust",
    repoStars: 100300,
    repoTopics: ["javascript", "typescript", "runtime"],
    whyRecommended: [
      "Primary language is Rust — matches your stack.",
      "Marked as a good first issue — ideal for new contributors.",
      "Established project with 100,300 stars.",
      "Active discussion on approach.",
    ],
    difficulty: "beginner",
    matchedLabels: ["Rust", "Beginner Friendly", "Help Wanted"],
    readme: {
      hasContributionGuide: true,
      setupComplexity: "moderate",
      techStack: ["rust", "javascript", "typescript"],
      architectureKeywords: ["plugin-system", "async"],
    },
    matchScore: {
      total: 72,
      breakdown: [
        { label: "Rust primary", points: 30, category: "language" as const },
        { label: "Good First Issue", points: 10, category: "issue" as const },
        { label: "Help Wanted", points: 5, category: "issue" as const },
        {
          label: "Established project",
          points: 12,
          category: "project" as const,
        },
        {
          label: "Contribution guide",
          points: 8,
          category: "project" as const,
        },
        { label: "Active discussion", points: 3, category: "issue" as const },
        { label: "Trending now", points: 7, category: "project" as const },
      ],
    },
    readinessScore: 80,
  },
];

export const mockRecommendations: Recommendation[] = baseRecommendations.map(
  (rec) => ({
    ...rec,
    effort: estimateEffort({
      difficulty: rec.difficulty,
      flags: deriveLabelFlags(rec.labels),
      comments: rec.comments,
      issueAge: 5,
      stars: rec.repoStars,
      readme: rec.readme,
    }),
  }),
);
